# Generated by Django 4.1.4 on 2022-12-13 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Titulo')),
                ('description', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('condition', models.CharField(choices=[('1', 'En proceso'), ('2', 'Pendiente'), ('3', 'Finalizado')], max_length=12, verbose_name='Estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('close_date', models.DateTimeField(auto_now=True, verbose_name='Fecha cierre')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_user')),
            ],
        ),
    ]
